[workspace]
authors = ["Charles Ciampa <ceciampa@gmail.com>"]
channels = ["conda-forge"]
name = "NLP_Final_Project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"
pandas = ">=2.2,<3"
numpy = ">=1.26,<2"
jupyterlab = ">=4.0,<5"
ipywidgets = ">=8.0,<9"
jupyterlab_widgets = ">=3.0,<4"

[pypi-dependencies]
torch = ">=2.4.0"
torchvision = ">=0.19.0"
torchaudio = ">=2.4.0"
transformers = ">=4.38"
accelerate = ">=0.28"
bitsandbytes = ">=0.43.0"
ollama = "*"
scikit-learn = "*"
seaborn = "*"
matplotlib = "*"
nltk = "*"
pyarrow = "*"
fsspec = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu124"]
