[workspace]
authors = ["Charles Ciampa <ceciampa@gmail.com>"]
channels = ["conda-forge"]
name = "NLP_Final_Project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
numpy = ">=2.3.4,<3"
python = ">=3.14.0,<3.15"
nltk = ">=3.9.2,<4"
scikit-learn = ">=1.7.2,<2"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.7,<4"
jupyterlab = ">=4.4.10,<5"
pyarrow = ">=22.0.0,<23"
fsspec = ">=2025.10.0,<2026"
huggingface_hub = ">=1.1.2,<2"
ipywidgets = ">=8.1.8,<9"
jupyterlab_widgets = ">=3.0.16,<4"

[pypi-dependencies]
ollama = ">=0.6.0, <0.7"
